steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/comfyui-nodepack"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "run"
      - "--env"
      - "CUSTOM_NODE_URL=$_CUSTOM_NODE_URL"
      - "--env"
      - "CUSTOM_NODE_NAME=$_CUSTOM_NODE_NAME"
      - "--volume"
      - "./output:/tmp/output"
      - "--workdir"
      - "/tmp/output"
      - "gcr.io/$PROJECT_ID/comfyui"
      - "comfyui-dream-project.json"

images:
  - "gcr.io/$PROJECT_ID/comfyui-nodepack"

substitutions:
  _CUSTOM_NODE_NAME: "default-node-name"
  _CUSTOM_NODE_URL: "https://example.com/default-node.tar.gz"

options:
  logging: CLOUD_LOGGING_ONLY