steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/comfyui-nodepack"
      - "."

images:
  - "gcr.io/$PROJECT_ID/comfyui-nodepack"

options:
  logging: CLOUD_LOGGING_ONLY